version: '3.8'

services:
  sqlserver_db:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver_cont4bl3
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${SQL_PASS}
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - cont4bl3

  auth-service:
    build:
      context: ${AUTH_PATH}
    container_name: auth-service
    ports:
      - "3000:3000"
    depends_on:
      - sqlserver_db
    environment:
      - DB_HOST=sqlserver_db
      - DB_PORT=1433
      - DB_USERNAME=${SQL_USER}
      - DB_PASSWORD=${SQL_PASS}
      - DB_NAME=auth_db
    entrypoint: ["sh", "-c", "sleep 20 && npm run start:prod"]
    networks:
      - cont4bl3

  contable-api:
    build:
      context: ${API_PATH}
    container_name: contable-api
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sqlserver_db:1433;databaseName=contable_db;encrypt=true;trustServerCertificate=true
      - SPRING_DATASOURCE_USERNAME=${SQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${SQL_PASS}
    entrypoint: ["sh", "-c", "sleep 20 && java -jar app.jar"]
    networks:
      - cont4bl3

  excel-service:
    build:
      context: ${EXCEL_PATH}
    container_name: excel-service
    ports:
      - "3001:3001"
    depends_on:
      - sqlserver_db
    environment:
      - DB_HOST=sqlserver_db
      - DB_PORT=1433
      - DB_USERNAME=${SQL_USER}
      - DB_PASSWORD=${SQL_PASS}
      - DB_NAME=contable_db
    networks:
      - cont4bl3

  cont4bl3_nginx:
    image: nginx:latest
    container_name: cont4bl3_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - cont4bl3

volumes:
  sqlserver_data:

networks:
  cont4bl3:
    external: true
